version: "3.7"

networks:
  nightingale:
    driver: bridge

services:
  mysql:
    image: "mariadb:10.9"
    container_name: mysql
    hostname: mysql
    restart: always
#    ports:
#      - "3306:3306"
    environment:
      TZ: Asia/Shanghai
      MARIADB_ROOT_PASSWORD: 1234
    volumes:
      - ./data/mysql:/var/lib/mysql/
      - ./initsql:/docker-entrypoint-initdb.d/
    networks:
      - nightingale

  redis:
    image: "redis:7"
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Shanghai
    networks:
      - nightingale
  
  victoriametrics:
    image: victoriametrics/victoria-metrics
    volumes:
      - ./data/victoriametrics:/victoria-metrics-data
    command: -retentionPeriod=3y

  ibex:
    image: ulric2019/ibex:0.3
    container_name: ibex
    hostname: ibex
    restart: always
    environment:
      GIN_MODE: release
      TZ: Asia/Shanghai
      WAIT_HOSTS: mysql:3306
    ports:
      - "10090:10090"
      - "20090:20090"
    volumes:
      - ./ibexetc:/app/etc
    networks:
      - nightingale
    depends_on:
      - mysql
    links:
      - mysql:mysql
    command: >
      sh -c "/wait && /app/ibex server"

  nwebapi:
    image: flashcatcloud/nightingale:latest
    container_name: nwebapi
    hostname: nwebapi
    restart: always
    environment:
      GIN_MODE: release
      TZ: Asia/Shanghai
      WAIT_HOSTS: mysql:3306, redis:6379
    volumes:
      - ./n9eetc:/app/etc
    ports:
      - "18000:18000"
    networks:
      - nightingale
    depends_on:
      - mysql
      - redis
      - victoriametrics
      - ibex
    links:
      - mysql:mysql
      - redis:redis
      - victoriametrics:victoriametrics
      - ibex:ibex
    command: >
      sh -c "/wait && /app/n9e webapi"

  nserver:
    image: flashcatcloud/nightingale:latest
    container_name: nserver
    hostname: nserver
    restart: always
    environment:
      GIN_MODE: release
      TZ: Asia/Shanghai
      WAIT_HOSTS: mysql:3306, redis:6379
    volumes:
      - ./n9eetc:/app/etc
    ports:
      - "19000:19000"
    networks:
      - nightingale
    depends_on:
      - mysql
      - redis
      - victoriametrics
      - ibex
    links:
      - mysql:mysql
      - redis:redis
      - victoriametrics:victoriametrics
      - ibex:ibex
    command: >
      sh -c "/wait && /app/n9e server"

  categraf:
    image: "flashcatcloud/categraf:latest"
    container_name: "categraf"
    hostname: "categraf01"
    restart: always
    environment:
      TZ: Asia/Shanghai
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_MOUNT_PREFIX: /hostfs
    volumes:
      - ./categraf/conf:/etc/categraf/conf
      - /:/hostfs
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9100:9100/tcp"
    networks:
      - nightingale
    depends_on:
      - nserver
    links:
      - nserver:nserver

  agentd:
    image: ulric2019/ibex:0.3
    container_name: agentd
    hostname: agentd
    restart: always
    environment:
      GIN_MODE: release
      TZ: Asia/Shanghai
    volumes:
      - ./ibexetc:/app/etc
    networks:
      - nightingale
    depends_on:
      - ibex
    links:
      - ibex:ibex
    command:
      - "/app/ibex"
      - "agentd"
